### ISSUE TITLE
ch55xtool.py file does not exist

### ISSUE THREAD

**Issue by hooppler** [ElectronicCats/arduino-wch58x#11]
When try to upload code to the board I get the following error. Code compilation works fine.

Arduino IDE
Version 2.3.2

Sketch uses 24040 bytes (5%) of program storage space. Maximum is 448000 bytes.
Global variables use 248 bytes (0%) of dynamic memory, leaving 31752 bytes for local variables. Maximum is 32000 bytes.
Failed uploading: cannot execute upload tool: exec: "{runtime.tools.MCS51Tools.path}/win/ch55xtool.py": file does not exist

**Comment by Marcelol52** [comment]
Hi, could you give us some more information on this issues? Like what board are you using or if this happens with any sketch? Feel free to add anything else that can help us replicate the issue, preferablly with screenshots.

**Comment by hooppler** [comment]
It seems that Arduino IDE on Windows is not supported :) . I found following in the documentation:
"You cannot use the Arduino IDE to compile to the board if your operating system is Windows. "

Maybe it would be convenient to add supported operating systems to README file.

Used board: TZT CH582M Development Board Core Board BLE Wireless Bluetooth 
(https://www.aliexpress.com/item/1005005305272257.html?spm=a2g0o.order_list.order_list_main.288.877b18026Tt6S5)
Operating system: Windows 10

I tried very simple program:
void setup() {
  // initialize digital pin 13 as an output.
  pinMode(13, OUTPUT);
}
// the loop function runs over and over again forever
void loop() {
  digitalWrite(13, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(100);              // wait for a second
  digitalWrite(13, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);              // wait for a second
}

Code uploads fine for NodeMcu.

**Comment by Marcelol52** [comment]
Hi @hooppler do you have any issues with compilation? The issue seems to only affect uploading to the boards. You can get the HEX file and use another method to upload to the board.

**Comment by hooppler** [comment]
No compiling issues, I tried to compile several Arduino IDE examples (File -> Examples ) and it works fine (Except that I need to substitute Serial with Serial2).
Also, I got hex file.

**Comment by hooppler** [comment]
@Marcelol52 Thanks for help, HEX file is uploading fine using wchispstudio.

**Comment by sabas1080** [comment]
we will switch to this tool @hooppler , thanks
