### ISSUE TITLE
Adding package to Arduino IDE

### ISSUE THREAD

**Issue by ITstreet1** [ElectronicCats/arduino-wch58x#8]
Can this package be added to Arduino IDE as a regular JSON package? If so, can you write the link?

Thank you.

**Comment by sabas1080** [comment]
Hi @ITstreet1 

we have added the link to the wiki

`https://electroniccats.github.io/Arduino_Boards_Index/package_electroniccats_index.json`

thanks for the comments

**Comment by ITstreet1** [comment]
Please add this info to the Readme file so someone else doesn't ask stupid questions, like me. :)

From what I have read, to use Windows I can not upload the sketch. I can only compile it, then use WCHISPStudio to upload HEX. 
Am I right? Will this be fixed in near future?

And besides, your support is for CH583 as that is what I get after installing the package. But on the image, there is a CH582.
???

**Comment by sabas1080** [comment]
@ITstreet1 

- I updated README with link to wiki
- yes, we will update to upload firmware automatically
- CH583 and CH582 are very similar, our tests were on the ch582

Thanks for your feedback
