### ISSUE TITLE
Wrong dependency name in package_electroniccats_index.json

### ISSUE THREAD

**Issue by GEEKiDoS** [ElectronicCats/arduino-wch58x#9]
`CH58x-HAL` was incorrectly spelled as `CH85x-HAL` causes `Error: 9 FAILED_PRECONDITION: Platform 'electroniccats:wch@0.0.1' not found: getting tool dependencies for platform electroniccats:wch@0.0.1: tool CH58x-HAL not found` error when installing board in arduino IDE

**Comment by xpeqex** [comment]
Hi @GEEKiDoS 

Thank you for reporting the issue. We apologize for any inconvenience caused, we will fix it as soon as possible. 
Would you like to receive a notification when the problem is resolved? 
If you have any other questions, feel free to ask.

Kind regards.
